GET http://localhost:3000

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/60b21d1676676d2eb802ae47

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Test",
    "email": "test@test.com",
    "password": "12345",
    "accountType": "Student"
}

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Test2",
    "email": "test2@test.com",
    "password": "12345",
    "accountType": "Tutor"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

###
POST http://localhost:3000/users/passwordReset
Content-Type: application/json

{
    "email": "lim071@hotmail.com"
}

###
POST http://localhost:3000/assess/submit
Content-Type: application/json

{
    "studentEmail": "test@test.com",
    "tutorEmail": "testTutor@test.com",
    "levelID": "0-0",
    "marks": {
        "amountOfTime": "8",
        "efficiency": "8",
        "correctness": "8",
        "attemptsTaken": "8"
    }
}

###

POST http://localhost:3000/users/submit
Content-Type: application/json

{
    "email": "test@test.com",
    "solutions": {
        "levelID": "0-0",
        "code": "move A1 30\\nmove B1 30",
        "attempts": 1,
        "stepsTaken": 15,
        "timeTaken": 20,
        "codeErrors": [{
            "id": 0,
            "type": "test",
            "message": "Test error",
            "lineOfError": 2
        }]
    }
}

###
DELETE http://localhost:3000/users/612910873714ca54bcdaf5e5

###
PATCH http://localhost:3000/users/60b22082422f381414720c5e
Content-Type: application/json

{
    "name": "New Test Name"
}

###
GET http://byte-harvester-server.herokuapp.com:80/
###
GET http://byte-harvester-server.herokuapp.com:80/users
###